import { ServiceCapability, ServiceTier } from "@/types/services";

export const SERVICES_DATA: ServiceCapability[] = [
  {
    id: "srv-01",
    title: "Executive & VIP Dignitary Protection",
    slug: "executive-protection",
    category: "executive-protection",
    summary: "Discrete, armed, low-profile and high-profile security details for corporate executives, high-net-worth families, and public figures.",
    fullDescription: "Built on U.S. Army Ranger perimeter doctrine and counter-surveillance protocols. Details include advance route reconnaissance, threat intelligence assessments, secure transport coordination, and immediate defensive extraction readiness.",
    responseSLA: "Immediate standby / Under 2-hour mobilization",
    armedRequirement: "Special Operations Operator",
    protocols: [
      "Advance route survey & medical evacuation corridors",
      "Counter-surveillance and motorcade security",
      "Close-in armed protection detail (Plainclothes or tactical)",
      "Secure encrypted comms with tactical operations center",
    ],
    keyHighlights: [
      "23+ years direct executive protection track record",
      "Vetted combat veteran details",
      "Discretion & Non-Disclosure guarantee",
    ],
    deploymentZones: ["Palm Beach", "Miami-Dade", "Treasure Coast", "Statewide FL"],
  },
  {
    id: "srv-02",
    title: "High-Stakes Combat & Major Event Security",
    slug: "event-security",
    category: "event-security",
    summary: "Battle-tested crowd management, ring-side security, and artist protection for world-class combat sports (BKFC) and stadium events.",
    fullDescription: "Specialized in high-energy, volatile environments where split-second de-escalation and decisive physical control are paramount. Trusted security provider for Bare Knuckle Fighting Championship (BKFC) arena events.",
    responseSLA: "Pre-planned scheduled deployment & dynamic rapid-response team",
    armedRequirement: "Armed (G License)",
    protocols: [
      "Ingress/egress choke-point control and metal detection screening",
      "Ringside, backstage, and VIP hospitality perimeter security",
      "Fighter/Talent escort & hostile crowd de-escalation",
      "Medical & local emergency service liaison command",
    ],
    keyHighlights: [
      "Official lead security detail for BKFC combat events",
      "Zero-tolerance breach track record in 10,000+ attendee venues",
      "Physical combatives certified team",
    ],
    deploymentZones: ["Fort Pierce", "Hollywood FL", "Miami", "Tampa", "Orlando"],
  },
  {
    id: "srv-03",
    title: "Commercial & High-Value Estate Mitigation",
    slug: "commercial-patrol",
    category: "commercial-patrol",
    summary: "Armed fixed-post and mobile patrol units safeguarding luxury estates, maritime docks, gated communities, and industrial infrastructure.",
    fullDescription: "Continuous physical presence and visible deterrence. Armed officers equipped with real-time GPS telemetry, incident body cams, thermal perimeter sweeps, and instant dispatch integration with local law enforcement.",
    responseSLA: "24/7/365 continuous deployment / 15-min patrol sweep intervals",
    armedRequirement: "Armed (G License)",
    protocols: [
      "Thermal sensor & boundary intrusion verification",
      "Marked tactical vehicle patrol & foot reconnaissance",
      "Access control logging & biometric visitor verification",
      "Night-vision dockside & maritime perimeter sweeps",
    ],
    keyHighlights: [
      "Real-time client telemetry dashboard access",
      "Class G licensed armed officers with tactical combat training",
      "Direct line to 24/7 Fort Pierce Command Center",
    ],
    deploymentZones: ["Fort Pierce", "Port St. Lucie", "Palm Beach County", "Stuart"],
  },
  {
    id: "srv-04",
    title: "Rapid Tactical Dispatch & Crisis Response",
    slug: "tactical-dispatch",
    category: "tactical-dispatch",
    summary: "Emergency surge response for active threats, executive panic alerts, labor disputes, and severe facility vulnerability incidents.",
    fullDescription: "When standard private security is insufficient, Howl's Rapid Response Team deploys fully equipped tactical operators to establish instant perimeter control, secure assets, and neutralize hostile dynamics.",
    responseSLA: "Sub-45 minute emergency arrival (Treasure Coast / Palm Beach)",
    armedRequirement: "Special Operations Operator",
    protocols: [
      "Immediate unit vectoring from localized command posts",
      "Perimeter hardening and armed point-defense",
      "Asset lockdown and evacuation escort",
      "Real-time situation report telemetry to client leadership",
    ],
    keyHighlights: [
      "Dedicated 24/7 priority emergency line: (772) 940-4114",
      "Armored/Tactical fleet availability",
      "Direct coordination with county sheriffs & SWAT units",
    ],
    deploymentZones: ["Fort Pierce", "Palm Beach", "Vero Beach", "Martin County"],
  },
];

export const SERVICE_TIERS: ServiceTier[] = [
  {
    name: "Tier 1: Asset Sentinel",
    code: "SEC-T1",
    description: "Standard armed perimeter security and continuous access control for commercial facilities and luxury residential estates.",
    features: [
      "Florida Class G armed officer presence",
      "Scheduled patrol sweeps with GPS verification",
      "Incident logging and digital daily shift reports",
      "Standard 24-hour dispatch coordination",
    ],
    idealFor: "Commercial plazas, gated residential communities, marinas, construction infrastructure.",
    priorityDispatch: false,
  },
  {
    name: "Tier 2: Executive Detail",
    code: "SEC-T2",
    description: "Specialized low-profile protective detail for high-net-worth individuals, corporate officers, and high-visibility events.",
    features: [
      "Military/Combat veteran certified protective agents",
      "Advance site survey and route threat modeling",
      "Discrete armed plainclothes escort",
      "Dedicated priority vehicle transport & counter-surveillance",
      "Priority 2-hour mobilization window",
    ],
    idealFor: "Corporate CEOs, visiting dignitaries, high-stakes litigation, private family protection.",
    priorityDispatch: true,
  },
  {
    name: "Tier 3: Tactical Overwatch & Combat Unit",
    code: "SEC-T3",
    description: "Maximum threat readiness tactical squad for volatile environments, high-capacity combat sports, and immediate crisis containment.",
    features: [
      "U.S. Army Ranger / SpecOps-led tactical squad",
      "Full combat gear, body armor, and unified radio command",
      "Ving Tsun combatives certified crowd & hostile breach management",
      "Real-time tactical command link to local law enforcement",
      "Sub-45 minute emergency dispatch SLA",
    ],
    idealFor: "BKFC & combat sports arenas, high-risk labor strikes, emergency asset evacuations.",
    priorityDispatch: true,
  },
];
