import { TrainingCourse } from "@/types/training";

export const TRAINING_COURSES: TrainingCourse[] = [
  {
    id: "vt-01",
    code: "VT-CQB-301",
    title: "Tactical Ving Tsun: Close-Quarters Hostile Control & Centerline Dominance",
    slug: "tactical-ving-tsun-cqb",
    category: "Ving Tsun Combatives",
    duration: "2 Days (16 Hours Intensive)",
    skillLevel: "Intermediate",
    prerequisites: ["Security License (D/G) OR Law Enforcement / Military ID OR Clean Background Check"],
    certificationsAwarded: ["Howl Tactical Combatives L1 Certificate", "8 FL DACS Continuing Ed Credits"],
    summary: "Distilling 30+ years of authentic Ving Tsun Kung Fu into brutal, highly efficient close-quarter protective tactics. Learn centerline theory, trapping hands, simultaneous attack/defense, and neutralizing violent attackers in phone-booth range.",
    curriculum: [
      {
        moduleNumber: 1,
        title: "Centerline Dominance & Stance Stability Under Stress",
        description: "Biomechanical leverage, redirecting incoming momentum, and maintaining balance against heavier aggressive assailants.",
        tacticsCovered: ["Yee Jee Kim Yeung Ma structure", "Pak Sao (Slapping Deflection)", "Tan Sao (Dispersing Force)", "Linear penetration footwork"],
      },
      {
        moduleNumber: 2,
        title: "Trapping Hands (Lop Sao / Chi Sao) in Tactical Scenarios",
        description: "Controlling limbs, clearing weapon access, and clearing obstacles in tight hallways, doorways, and crowds.",
        tacticsCovered: ["Lop Sao wrist/forearm entrapment", "Biu Jee eye/throat line disruption", "Tactical elbow & knee strikes", "Wall pinning"],
      },
      {
        moduleNumber: 3,
        title: "Hostile Extraction & Non-Lethal Suspect Compliance",
        description: "Taking control of violent subjects without collateral damage or liability.",
        tacticsCovered: ["Joint lock transitions", "Double arm drag to prone restraint", "Team takedown integration"],
      },
    ],
    gearRequirements: ["Mouthguard", "MMA Sparring Gloves (4-7oz)", "Tactical boots or training shoes", "Duty belt (inert)"],
    nextDate: "September 18-19, 2026",
    tuition: "$495.00",
    seatsAvailable: 8,
  },
  {
    id: "vt-02",
    code: "VT-EDG-402",
    title: "Edged Weapon & Contact Distance Defensive Survival",
    slug: "edged-weapon-defense",
    category: "Ving Tsun Combatives",
    duration: "1 Day (8 Hours)",
    skillLevel: "Advanced / Law Enforcement Only",
    prerequisites: ["Prior Hand-to-Hand Combatives Experience", "Active Security/LE Credential"],
    certificationsAwarded: ["Howl Edged Weapon Countermeasures Specialist"],
    summary: "Realistic, zero-nonsense defense against ambush knife thrusts, slashes, and close-proximity weapon retention using continuous centerline pressure and deflection.",
    curriculum: [
      {
        moduleNumber: 1,
        title: "The Anatomy of a Blade Ambush & Reactionary Gap",
        description: "Understanding realistic knife attacks vs fantasy choreography.",
        tacticsCovered: ["Bong Sao angle deflection", "2-on-1 wrist lockdown", "Shock mitigation"],
      },
      {
        moduleNumber: 2,
        title: "Weapon Retention & Holster Defense",
        description: "Preventing gun grabs during physical scuffles in crowd situations.",
        tacticsCovered: ["High-retention draw", "Elbow frame protection", "Centerline counter-strikes"],
      },
    ],
    gearRequirements: ["Shock knife or rubber training blade", "Eye protection", "Duty gear"],
    nextDate: "October 10, 2026",
    tuition: "$295.00",
    seatsAvailable: 6,
  },
  {
    id: "vt-03",
    code: "EP-TAC-501",
    title: "Executive Protection Agent Academy & Motorcade Formations",
    slug: "executive-protection-academy",
    category: "Executive Protection",
    duration: "5 Days (40 Hours Intensive)",
    skillLevel: "Advanced / Law Enforcement Only",
    prerequisites: ["Florida Class G License OR Military/LE Veteran Status", "Clean Background Check"],
    certificationsAwarded: ["Howl Certified Executive Protection Specialist (CEPS)", "FL Class G Recertification eligible"],
    summary: "Comprehensive bodyguard and dignitary protection course covering advance work, motorcade driving drills, tactical walk formations, threat intelligence, and emergency evac under fire.",
    curriculum: [
      {
        moduleNumber: 1,
        title: "Advance Work & Threat Matrix Analysis",
        description: "Pre-arrival site security surveys, emergency medical staging, and venue reconnaissance.",
        tacticsCovered: ["Route mapping", "Safe room identification", "Local emergency protocol coordination"],
      },
      {
        moduleNumber: 2,
        title: "Walking Formations & Principal Cover-and-Evacuate",
        description: "Diamond, box, and wedge formations in public crowds.",
        tacticsCovered: ["Body shield positioning", "Immediate action drills (IAD)", "Vehicle embus/debus"],
      },
    ],
    gearRequirements: ["Concealed carry holster", "Business suit / tactical attire", "Eye & ear protection", "500 rounds factory ammo"],
    nextDate: "November 4-8, 2026",
    tuition: "$1,450.00",
    seatsAvailable: 4,
  },
];
