export const COMPANY_INFO = {
  name: "HOWL SECURITY GROUP",
  shortName: "HOWL",
  tagline: "VIGILANCE. STRENGTH. UNITY.",
  founder: {
    name: "Gerald Hazellief",
    title: "US Army Ranger Veteran & Founder",
    experienceYears: 23,
    martialArtsYears: 30,
    specialties: [
      "Special Operations Combat Veteran (75th Ranger Regiment Tradition)",
      "Ving Tsun (Wing Chun) Kung Fu Master Lineage",
      "Executive & Dignitary Protection Lead",
      "Bare Knuckle Fighting Championship (BKFC) Lead Event Security Detail",
      "High-Threat CQB & Edged Weapon Countermeasures Instructor",
    ],
    bio: "Founded on the uncompromising discipline of U.S. Army Special Operations and decades of pure Ving Tsun combatives mastery. Howl Security Group delivers preemptive threat mitigation, physical asset protection, and executive security across South Florida with zero compromise.",
  },
  contact: {
    phoneFormatted: "+1 (772) 940-4114",
    phoneDisplay: "(772) 940-4114",
    phoneRaw: "+17729404114",
    email: "dispatch@howlsecuritygroup.com",
    address: {
      hq: "Fort Pierce Tactical Operations Center",
      city: "Fort Pierce",
      state: "FL",
      region: "South Florida & Treasure Coast",
    },
    coverageRegions: [
      "Fort Pierce",
      "Port St. Lucie",
      "Palm Beach",
      "Boca Raton",
      "Stuart / Martin County",
      "Vero Beach / Indian River",
      "Miami-Dade Operational Sector",
    ],
    licensing: "Florida State Security Agency Class B/G/M Licensed & Insured",
  },
  tickerItems: [
    "23+ YEARS EXECUTIVE PROTECTION",
    "U.S. ARMY RANGER VETERAN",
    "BKFC FIGHT DETAIL SECURITY",
    "30+ YEARS COMBATIVES MASTER",
    "FORT PIERCE & PALM BEACH DISPATCH",
    "FL STATE LICENSED CLASS G ARMED DETAIL",
    "ZERO-TOLERANCE THREAT MITIGATION",
  ],
};
